### PR TITLE
Sanitize readme

### PR DESCRIPTION
**Pull request by xbrianh**

### CODE REVIEW

**Review by juklucas — APPROVED** [review]
LGTM.

+1 for "super"

**Review by aofarrel — CHANGES_REQUESTED** [review]
You forgot "serendipitous."

**Comment by xbrianh** [comment]
> You forgot "serendipitous."

fixed!

**Review by aofarrel — APPROVED** [review]
Thanks for patching this so quickly!

**Review by bethsheets — COMMENTED** [review]
LGTM

**Pull request merged**
